import type { Category, Product, ProductStatus } from "./types";

// Demonstration details only. Replace prices, sizing and availability on database handoff.
const entries: [
  string,
  string,
  number,
  string,
  ProductStatus,
  string[],
  string,
  Category?,
][] = [
  [
    "Crimson Web Hoodie",
    "crimson-web-hoodie",
    2800,
    "L",
    "available",
    ["feature-jacket-2", "10"],
    "Black / crimson",
  ],
  [
    "Split Identity Jacket",
    "split-identity-jacket",
    2600,
    "L",
    "available",
    ["feature-jacket-1", "7"],
    "Washed black",
  ],
  [
    "Friendly Neighborhood",
    "friendly-neighborhood",
    2400,
    "M",
    "available",
    ["feature-jacket-3", "11"],
    "Light indigo / red",
  ],
  [
    "Scarlet Spider Jacket",
    "scarlet-spider-jacket",
    2900,
    "L",
    "sold",
    ["feature-jacket-4"],
    "Deep indigo / red",
  ],
  [
    "Shadow Study Jacket",
    "shadow-study-jacket",
    2700,
    "XL",
    "available",
    ["feature-jacket-5", "12"],
    "Washed indigo",
  ],
  [
    "Blue Cybersigil Hoodie",
    "blue-cybersigil-hoodie",
    3200,
    "L",
    "available",
    ["blue-cybersigilisim-denim-hoodie-jacket"],
    "Black / cobalt",
  ],
  [
    "Cross Signal Jacket",
    "cross-signal-jacket",
    3000,
    "M",
    "available",
    ["cross-cybersigilism-denim-jacket"],
    "Black / silver",
  ],
  [
    "Webwork Denim",
    "webwork-denim",
    3100,
    "L",
    "sold",
    ["spiderman-x-cybersigilism-denim-jacket"],
    "Black / red",
  ],
  [
    "Straw Hat Denim Hoodie",
    "straw-hat-denim-hoodie",
    3400,
    "XL",
    "sold",
    ["luffy-one-piece-denim-hoodie-jacket"],
    "Indigo / cream",
  ],
  [
    "Three Sword Denim Hoodie",
    "three-sword-denim-hoodie",
    3400,
    "L",
    "archived",
    ["zoro-one-piece-denim-hoodie-jacket"],
    "Light indigo / cream",
  ],
  [
    "Webhead Tee",
    "webhead-tee",
    1200,
    "M",
    "available",
    ["5"],
    "Washed black / red",
    "Tops",
  ],
  [
    "Midnight Spider",
    "midnight-spider",
    2600,
    "L",
    "archived",
    ["14"],
    "Black / silver",
  ],
];
export const localProducts: Product[] = entries.map(
  ([name, slug, price, size, status, images, color, category], i) => ({
    id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
    name,
    slug,
    price,
    size,
    status,
    color,
    category: category ?? "Jackets",
    description:
      "Selected denim, given a new identity. Hand-painted artwork follows the shape of the garment, making the piece an individual expression. Natural wear and variations are part of its character.",
    condition: "Reworked vintage · details on inquiry",
    material:
      category === "Tops"
        ? "Cotton jersey · composition to confirm"
        : "Denim · composition to confirm",
    featured: i < 3,
    bestseller: i < 6,
    created_at: `2026-08-${String(28 - i).padStart(2, "0")}T00:00:00Z`,
    updated_at: "2026-08-28T00:00:00Z",
    images: images.map((image) => `/images/${image}.webp`),
    image_alt: `${name} — hand-painted ${color.toLowerCase()} ${category === "Tops" ? "tee" : "denim jacket"}`,
    measurements: [
      { label: "Chest (laid flat)", value: "Confirm on inquiry" },
      { label: "Body length", value: "Confirm on inquiry" },
      { label: "Sleeve length", value: "Confirm on inquiry" },
    ],
    care: "Gently spot clean when possible. Cold hand wash inside out with mild detergent. Air dry in the shade. Do not bleach, tumble dry, or iron directly over the artwork. Confirm piece-specific care before washing.",
    drop: "STUDY 01 / 2026",
  }),
);
export const categories: Category[] = [
  "Jackets",
  "Pants",
  "Tops",
  "Accessories",
  "Custom",
];
export const formatPrice = (price: number) =>
  `PHP ${new Intl.NumberFormat("en-PH", { maximumFractionDigits: 0 }).format(price)}`;
